// Generated by gencpp from file service_generator/DinoFactGenerator.msg
// DO NOT EDIT!


#ifndef SERVICE_GENERATOR_MESSAGE_DINOFACTGENERATOR_H
#define SERVICE_GENERATOR_MESSAGE_DINOFACTGENERATOR_H

#include <ros/service_traits.h>


#include <service_generator/DinoFactGeneratorRequest.h>
#include <service_generator/DinoFactGeneratorResponse.h>


namespace service_generator
{

struct DinoFactGenerator
{

typedef DinoFactGeneratorRequest Request;
typedef DinoFactGeneratorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DinoFactGenerator
} // namespace service_generator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_generator::DinoFactGenerator > {
  static const char* value()
  {
    return "45c86d5d7dfcd02fa17ec95f669893aa";
  }

  static const char* value(const ::service_generator::DinoFactGenerator&) { return value(); }
};

template<>
struct DataType< ::service_generator::DinoFactGenerator > {
  static const char* value()
  {
    return "service_generator/DinoFactGenerator";
  }

  static const char* value(const ::service_generator::DinoFactGenerator&) { return value(); }
};


// service_traits::MD5Sum< ::service_generator::DinoFactGeneratorRequest> should match
// service_traits::MD5Sum< ::service_generator::DinoFactGenerator >
template<>
struct MD5Sum< ::service_generator::DinoFactGeneratorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_generator::DinoFactGenerator >::value();
  }
  static const char* value(const ::service_generator::DinoFactGeneratorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_generator::DinoFactGeneratorRequest> should match
// service_traits::DataType< ::service_generator::DinoFactGenerator >
template<>
struct DataType< ::service_generator::DinoFactGeneratorRequest>
{
  static const char* value()
  {
    return DataType< ::service_generator::DinoFactGenerator >::value();
  }
  static const char* value(const ::service_generator::DinoFactGeneratorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_generator::DinoFactGeneratorResponse> should match
// service_traits::MD5Sum< ::service_generator::DinoFactGenerator >
template<>
struct MD5Sum< ::service_generator::DinoFactGeneratorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_generator::DinoFactGenerator >::value();
  }
  static const char* value(const ::service_generator::DinoFactGeneratorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_generator::DinoFactGeneratorResponse> should match
// service_traits::DataType< ::service_generator::DinoFactGenerator >
template<>
struct DataType< ::service_generator::DinoFactGeneratorResponse>
{
  static const char* value()
  {
    return DataType< ::service_generator::DinoFactGenerator >::value();
  }
  static const char* value(const ::service_generator::DinoFactGeneratorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_GENERATOR_MESSAGE_DINOFACTGENERATOR_H
